In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [2]:
a = np.array([[1,2,3], [2,4,6]])
print(a)
np.average(a, axis=0)

[[1 2 3]
 [2 4 6]]


array([1.5, 3. , 4.5])

In [3]:
from scipy import stats
stats.norm.ppf(0.975)

1.959963984540054

In [4]:
a = np.array([1,2,3, 2,4,6])
print(a)
_a = a.reshape(3,2)
print(_a)
np.average(_a, axis=1)

[1 2 3 2 4 6]
[[1 2]
 [3 2]
 [4 6]]


array([1.5, 2.5, 5. ])

In [5]:
a1 = np.array([1,2,3])
a2 = np.array([1,2,5])
np.concatenate([a1, a2])

array([1, 2, 3, 1, 2, 5])

In [6]:
a = 2

{{a}}